name: identity_firebase_github
description: Github SSO by Firebase for Identity package
version: 0.2.0
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-github

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.2.0
  identity: ^0.2.0
  identity_firebase: ^0.2.0
  firebase_auth: ^0.15.3
  github_sign_in: ^0.0.1

flutter:
  assets:
    - images/github.png
